/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeTask;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Maa
 */
public class Edit_Customer extends javax.swing.JPanel {

    /**
     * Creates new form Edit_Customer
     */
    public Edit_Customer() {
        initComponents();
        empnamelb.setText(Employeedash.Empname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditEmp_panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        edit_addresstxt = new javax.swing.JTextArea();
        edit_fathernametxt = new javax.swing.JTextField();
        dobtxt = new javax.swing.JTextField();
        mobiletxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maleradio = new javax.swing.JRadioButton();
        femaleradio = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        edit_find = new javax.swing.JButton();
        acnotxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        edit2_reset = new javax.swing.JButton();
        edit_update = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        edit_nametxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        citytxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pintxt = new javax.swing.JTextField();
        statetxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        empnamelb = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EditEmp_panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EditEmp_panel.setMinimumSize(new java.awt.Dimension(658, 537));
        EditEmp_panel.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Father's Name");
        EditEmp_panel.add(jLabel13);
        jLabel13.setBounds(50, 150, 100, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Gender");
        EditEmp_panel.add(jLabel14);
        jLabel14.setBounds(50, 190, 90, 30);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Mobile No.");
        EditEmp_panel.add(jLabel15);
        jLabel15.setBounds(50, 300, 70, 30);

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setText("Email id");
        EditEmp_panel.add(jLabel17);
        jLabel17.setBounds(50, 260, 110, 30);

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setText("Address");
        EditEmp_panel.add(jLabel18);
        jLabel18.setBounds(50, 350, 90, 30);

        edit_addresstxt.setColumns(20);
        edit_addresstxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        edit_addresstxt.setRows(5);
        edit_addresstxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(edit_addresstxt);
        edit_addresstxt.setBounds(170, 340, 200, 70);

        edit_fathernametxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        edit_fathernametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(edit_fathernametxt);
        edit_fathernametxt.setBounds(170, 150, 250, 30);

        dobtxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dobtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(dobtxt);
        dobtxt.setBounds(170, 220, 200, 30);

        mobiletxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mobiletxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(mobiletxt);
        mobiletxt.setBounds(170, 300, 200, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("* Including sur name");
        EditEmp_panel.add(jLabel2);
        jLabel2.setBounds(30, 490, 180, 14);

        maleradio.setText("Male");
        maleradio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        maleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleradioActionPerformed(evt);
            }
        });
        EditEmp_panel.add(maleradio);
        maleradio.setBounds(200, 190, 70, 20);

        femaleradio.setText("Female");
        femaleradio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        femaleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleradioActionPerformed(evt);
            }
        });
        EditEmp_panel.add(femaleradio);
        femaleradio.setBounds(320, 190, 80, 20);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setPreferredSize(new java.awt.Dimension(570, 130));

        edit_find.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        edit_find.setText("Find");
        edit_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_findActionPerformed(evt);
            }
        });

        acnotxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        acnotxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setText("Account no");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(acnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(edit_find, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_find, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        EditEmp_panel.add(jPanel6);
        jPanel6.setBounds(40, 20, 550, 80);

        edit2_reset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        edit2_reset.setIcon(new javax.swing.ImageIcon("E:\\project\\erase-128.png")); // NOI18N
        edit2_reset.setText("Reset");
        edit2_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2_resetActionPerformed(evt);
            }
        });
        EditEmp_panel.add(edit2_reset);
        edit2_reset.setBounds(460, 150, 100, 30);

        edit_update.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        edit_update.setIcon(new javax.swing.ImageIcon("E:\\project\\update icon.png")); // NOI18N
        edit_update.setText("Update");
        edit_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_updateActionPerformed(evt);
            }
        });
        EditEmp_panel.add(edit_update);
        edit_update.setBounds(460, 110, 100, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Full Name*");
        EditEmp_panel.add(jLabel10);
        jLabel10.setBounds(50, 110, 100, 30);

        edit_nametxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        edit_nametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edit_nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_nametxtActionPerformed(evt);
            }
        });
        EditEmp_panel.add(edit_nametxt);
        edit_nametxt.setBounds(170, 110, 250, 30);

        emailtxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        emailtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(emailtxt);
        emailtxt.setBounds(170, 260, 250, 30);

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel20.setText("Date of Birth");
        EditEmp_panel.add(jLabel20);
        jLabel20.setBounds(50, 220, 100, 30);

        jLabel4.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel4.setText("city");
        EditEmp_panel.add(jLabel4);
        jLabel4.setBounds(390, 300, 50, 30);

        citytxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(citytxt);
        citytxt.setBounds(470, 300, 110, 30);

        jLabel21.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel21.setText("State");
        EditEmp_panel.add(jLabel21);
        jLabel21.setBounds(390, 340, 50, 30);

        jLabel11.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel11.setText("Pin");
        EditEmp_panel.add(jLabel11);
        jLabel11.setBounds(390, 380, 50, 30);

        pintxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pintxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pintxtActionPerformed(evt);
            }
        });
        EditEmp_panel.add(pintxt);
        pintxt.setBounds(470, 380, 110, 30);

        statetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        statetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statetxtActionPerformed(evt);
            }
        });
        EditEmp_panel.add(statetxt);
        statetxt.setBounds(470, 340, 110, 30);

        jLabel22.setText("* Please keep dob (yyyy-mm-dd)");
        EditEmp_panel.add(jLabel22);
        jLabel22.setBounds(390, 230, 160, 14);

        add(EditEmp_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 700, 460));

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        jLabel3.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        jLabel3.setText("Edit Customer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, -1, -1));

        jLabel38.setFont(new java.awt.Font("Century", 0, 11)); // NOI18N
        jLabel38.setText("Logged in As :");
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        empnamelb.setFont(new java.awt.Font("Century", 0, 11)); // NOI18N
        empnamelb.setText("emp");
        add(empnamelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void edit_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_findActionPerformed
        try{
            Main.Database ob= new Main.Database();
             try{
            Class.forName(ob.Driver);
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex);
            }
            Connection con=DriverManager.getConnection(ob.Url+ob.Db,ob.Userid,ob.Password);
            Statement st=con.createStatement();
            String query="Select *from customer where Ac_no='"+acnotxt.getText()+"'";

            ResultSet rs=st.executeQuery(query);
            while(rs.next()){
                edit_nametxt.setText(rs.getString(2));
                edit_fathernametxt.setText(rs.getString(3));
                
               
                if(rs.getString(4).equals("male")){
                 maleradio.setSelected(true);  
                }
                else{
                    femaleradio.setSelected(true);
                }
                String date=rs.getString(5);
                dobtxt.setText(date);
                mobiletxt.setText(rs.getString(6));
                emailtxt.setText(rs.getString(7));
                edit_addresstxt.setText(rs.getString(8));
                 citytxt.setText(rs.getString(9));
                statetxt.setText(rs.getString(10));
                pintxt.setText(rs.getString(11));
            }

        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }        // TODO addemp your handling code here:
    }//GEN-LAST:event_edit_findActionPerformed

    private void edit_nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_nametxtActionPerformed
        // TODO addemp your handling code here:
    }//GEN-LAST:event_edit_nametxtActionPerformed

    private void edit2_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2_resetActionPerformed
        edit_nametxt.setText("");
        acnotxt.setText("");
        edit_fathernametxt.setText("");
        maleradio.setSelected(false);
        femaleradio.setSelected(false);
        emailtxt.setText("");

        dobtxt.setText("");
        mobiletxt.setText("");
        edit_addresstxt.setText("");
        citytxt.setText("");
                statetxt.setText("");
                pintxt.setText("");
    }//GEN-LAST:event_edit2_resetActionPerformed

    private void edit_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_updateActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
            Main.Database ob=new Main.Database();
            Class.forName(ob.Driver);
            Connection con=DriverManager.getConnection(ob.Url+ob.Db,ob.Userid,ob.Password);

            String query="Update Customer set Name =?,Father_name=?,gender=?,dob=?,Mobile_no=?,Email_id=?,address=?,city=?,state=?,pin=? where Ac_no='"+acnotxt.getText()+"'";
            PreparedStatement pst=con.prepareStatement(query);

            pst.setString(1, edit_nametxt.getText());
            pst.setString(2,edit_fathernametxt.getText());
            String gender;
            if(femaleradio.isSelected()){
                gender="female";}
            else{
                gender="male"; }
            pst.setString(3,gender);
            pst.setString(4,dobtxt.getText());
           pst.setString(5,mobiletxt.getText());
            pst.setString(6,emailtxt.getText());
            pst.setString(7,edit_addresstxt.getText());
            pst.setString(8,citytxt.getText());
            pst.setString(9,statetxt.getText());
            pst.setString(10,pintxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Update Successful");
        }

        catch( ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }   // TODO addemp your handling code here:
    }//GEN-LAST:event_edit_updateActionPerformed

    private void statetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statetxtActionPerformed

    private void pintxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pintxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pintxtActionPerformed

    private void maleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleradioActionPerformed
       if(maleradio.isSelected())
        {
            femaleradio.setSelected(false); } // TODO add your handling code here:
    }//GEN-LAST:event_maleradioActionPerformed

    private void femaleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleradioActionPerformed
      if(femaleradio.isSelected())
        {
            maleradio.setSelected(false); }  // TODO add your handling code here:
    }//GEN-LAST:event_femaleradioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EditEmp_panel;
    private javax.swing.JTextField acnotxt;
    private javax.swing.JTextField citytxt;
    private javax.swing.JTextField dobtxt;
    private javax.swing.JButton edit2_reset;
    private javax.swing.JTextArea edit_addresstxt;
    private javax.swing.JTextField edit_fathernametxt;
    private javax.swing.JButton edit_find;
    private javax.swing.JTextField edit_nametxt;
    private javax.swing.JButton edit_update;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel empnamelb;
    private javax.swing.JRadioButton femaleradio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton maleradio;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField pintxt;
    private javax.swing.JTextField statetxt;
    // End of variables declaration//GEN-END:variables
}
