/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerTask;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Maa
 */
public class Transfer extends javax.swing.JPanel {

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
        CustomerTask.User user =new CustomerTask.User();
        acnotxt.setText(user.customerno);
        customerlb.setText(User.name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        namelbb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        avlballb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        namelb = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        acnotxt = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        customerlb = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        jLabel2.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        jLabel2.setText("Transfer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(465, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, -1, 60));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel3.setText("Account No");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 110, 30));

        jLabel4.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel4.setText("Benificiary Accont number");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 210, 31));

        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel3.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 210, 29));

        jLabel8.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel8.setText("Beneficiary Name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 140, 30));

        jButton6.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jButton6.setText("transfer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 140, 30));

        jButton1.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 90, 30));

        jLabel5.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel5.setText("Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 60, 30));
        jPanel3.add(namelbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 210, 30));

        jLabel6.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel6.setText("Avl. Balance");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 100, 30));
        jPanel3.add(avlballb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 150, 30));

        jButton2.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jButton2.setText("Check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 90, 30));
        jPanel3.add(namelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 200, 30));

        jLabel9.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jLabel9.setText("Amount");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 70, 30));
        jPanel3.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 210, 30));

        acnotxt.setEditable(false);
        jPanel3.add(acnotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 210, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 119, 680, 440));

        jLabel31.setText("Logged in As :");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        customerlb.setText("emp");
        jPanel1.add(customerlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
 try{
         CustomerTask.User user =new CustomerTask.User();
            Main.Database ob= new Main.Database();
            Connection con=DriverManager.getConnection(ob.Url+ob.Db,ob.Userid,ob.Password);
            Statement st=con.createStatement();
            String query="Select *from customer where Ac_no='"+user.customerno+"'";

            ResultSet rs=st.executeQuery(query);
            while(rs.next()){
                namelb.setText(rs.getString(2));
           }
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }  
     try {
          Main.Database ob= new Main.Database();
           Class.forName(ob.Driver);
            Connection con=DriverManager.getConnection(ob.Url+ob.Db,ob.Userid,ob.Password);
           
       Statement st = con.createStatement();
       CustomerTask.User user =new CustomerTask.User();
      String query = "select sum(amount) from Emptransaction where Ac_no='"
              + user.customerno + "' and ttype='d'";
      ResultSet rs = st.executeQuery(query);
      int dip = 0;
      if (rs.next()) {
        if (rs.getString(1) != null) {
            try
            {
          dip = Integer.parseInt(rs.getString(1));
            }catch(Exception ex){}
          query = "select sum(amount) from emptransaction where Ac_no='"
                  +user.customerno + "' and ttype='w'";
          rs = st.executeQuery(query);
          int with = 0;
          if (rs.next()) {
              try
              {
            with = Integer.parseInt(rs.getString(1));
              }
              catch(Exception ex){}
          }
           int bal = dip - with;
          avlballb.setText("" + bal);
        }else{
            avlballb.setText("" + "0");
        }
       }
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Error " + e);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
            Main.Database ob= new Main.Database();
            Connection con=DriverManager.getConnection(ob.Url+ob.Db,ob.Userid,ob.Password);
            Statement st=con.createStatement();
            CustomerTask.User user =new CustomerTask.User();
            String query="Select *from customer where Ac_no='"+t2.getText()+"'";

            ResultSet rs=st.executeQuery(query);
            while(rs.next()){
                namelbb.setText(rs.getString(2));
           }
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try {

          
          String amount = t3.getText().trim();
          Main.Database ob= new Main.Database();
           Class.forName(ob.Driver);
           CustomerTask.User user =new CustomerTask.User();
            Connection con=DriverManager.getConnection(ob.Url+ob.Db,ob.Userid,ob.Password);
        Statement st=con.createStatement();
          String query = "select sum(amount) from emptransaction where ac_no='"
                  + user.customerno+ "' and ttype='d'";
          ResultSet rs = st.executeQuery(query);
          rs.next();
          int dip = 0;
          try {
              dip = Integer.parseInt(rs.getString(1));
          } catch (Exception ex) {
          }
      

          query = "select sum(amount) from emptransaction where ac_no='"
                  + user.customerno + "' and ttype='w'";
          rs = st.executeQuery(query);
          rs.next();
          int with = 0;
          try {
              with = Integer.parseInt(rs.getString(1));
          } catch (Exception ex) {
          }
          //JOptionPane.showMessageDialog(null, "Total Withdrawal "+with);
          int bal = dip - with;

          if (bal >= Integer.parseInt(amount)) {
               String acno2=t2.getText();
              java.util.Date dt = new java.util.Date();
              String cdate = (dt.getYear() + 1900) + "-" + (dt.getMonth() + 1) + "-" + dt.getDate() + " "
                      + dt.getHours() + ":" + dt.getMinutes() + ":" + dt.getSeconds();

              query = "insert into emptransaction (tdate,ac_no,amount,ttype ) values ('"
                      + cdate + "','" + user.customerno + "','" + amount + "','w')";
              int re = st.executeUpdate(query);
              if (re > 0) {
                  JOptionPane.showMessageDialog(null, "Withdrawal from " + user.customerno + " success");
              }

              query = "insert into emptransaction (tdate,ac_no,amount,ttype ) values ('"
                      + cdate + "','" + acno2 + "','" + amount + "','d')";
              re = st.executeUpdate(query);
              if (re > 0) {
                  JOptionPane.showMessageDialog(null, "Deposited in " + t2.getText() + "  success");
              }
          }
          else
          {
              JOptionPane.showMessageDialog(null, "Not Sufficient Balance");
          }

      } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Error " + e);
      }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acnotxt;
    private javax.swing.JLabel avlballb;
    private javax.swing.JLabel customerlb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel namelb;
    private javax.swing.JLabel namelbb;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
