/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import AdminTask.Password;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author Maa
 */
public class CustomerTaskFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerTask_Main
     */
    public CustomerTaskFrame() {
        initComponents();
         container.removeAll();

        CustomerTask.Transfer ob=new CustomerTask.Transfer();
        container.setLayout(new CardLayout());

        container.add(ob);
        container.repaint();
        container.validate();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        Thred1 ob1;
        ob1 = new Thred1();
        ob1.start();
    }
    void setColor(JPanel panel)
    {
        panel.setBackground(new Color(51,0,51));
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(102,0,102));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        btn_transact = new javax.swing.JPanel();
        Add2 = new javax.swing.JLabel();
        btn_balance = new javax.swing.JPanel();
        Add4 = new javax.swing.JLabel();
        btn_transfer = new javax.swing.JPanel();
        Add3 = new javax.swing.JLabel();
        btn_about = new javax.swing.JPanel();
        Add5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_transfer1 = new javax.swing.JPanel();
        Add6 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(910, 620));
        setPreferredSize(new java.awt.Dimension(910, 620));

        bgpanel.setLayout(null);

        sidepanel.setBackground(new java.awt.Color(102, 0, 102));

        btn_transact.setBackground(new java.awt.Color(102, 0, 102));
        btn_transact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_transactMousePressed(evt);
            }
        });

        Add2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add2.setForeground(new java.awt.Color(255, 255, 255));
        Add2.setText("Transactions");

        javax.swing.GroupLayout btn_transactLayout = new javax.swing.GroupLayout(btn_transact);
        btn_transact.setLayout(btn_transactLayout);
        btn_transactLayout.setHorizontalGroup(
            btn_transactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_transactLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_transactLayout.setVerticalGroup(
            btn_transactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_balance.setBackground(new java.awt.Color(102, 0, 102));
        btn_balance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_balanceMousePressed(evt);
            }
        });

        Add4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add4.setForeground(new java.awt.Color(255, 255, 255));
        Add4.setText("Balance Enquiry");

        javax.swing.GroupLayout btn_balanceLayout = new javax.swing.GroupLayout(btn_balance);
        btn_balance.setLayout(btn_balanceLayout);
        btn_balanceLayout.setHorizontalGroup(
            btn_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_balanceLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add4)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        btn_balanceLayout.setVerticalGroup(
            btn_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_transfer.setBackground(new java.awt.Color(51, 0, 51));
        btn_transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_transferMousePressed(evt);
            }
        });

        Add3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add3.setForeground(new java.awt.Color(255, 255, 255));
        Add3.setText("Transfer");

        javax.swing.GroupLayout btn_transferLayout = new javax.swing.GroupLayout(btn_transfer);
        btn_transfer.setLayout(btn_transferLayout);
        btn_transferLayout.setHorizontalGroup(
            btn_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_transferLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_transferLayout.setVerticalGroup(
            btn_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_about.setBackground(new java.awt.Color(102, 0, 102));
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_aboutMousePressed(evt);
            }
        });

        Add5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add5.setForeground(new java.awt.Color(255, 255, 255));
        Add5.setText("About");

        javax.swing.GroupLayout btn_aboutLayout = new javax.swing.GroupLayout(btn_about);
        btn_about.setLayout(btn_aboutLayout);
        btn_aboutLayout.setHorizontalGroup(
            btn_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_aboutLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add5)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        btn_aboutLayout.setVerticalGroup(
            btn_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/results.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_transfer1.setBackground(new java.awt.Color(51, 0, 51));
        btn_transfer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_transfer1MousePressed(evt);
            }
        });

        Add6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add6.setForeground(new java.awt.Color(255, 255, 255));
        Add6.setText("change Password");

        javax.swing.GroupLayout btn_transfer1Layout = new javax.swing.GroupLayout(btn_transfer1);
        btn_transfer1.setLayout(btn_transfer1Layout);
        btn_transfer1Layout.setHorizontalGroup(
            btn_transfer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_transfer1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_transfer1Layout.setVerticalGroup(
            btn_transfer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidepanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addComponent(btn_transfer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btn_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_transact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btn_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(btn_about, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_transfer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidepanelLayout.createSequentialGroup()
                    .addGap(242, 242, 242)
                    .addComponent(btn_transact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btn_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        bgpanel.add(sidepanel);
        sidepanel.setBounds(0, 0, 234, 570);
        sidepanel.getAccessibleContext().setAccessibleDescription("");

        container.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        bgpanel.add(container);
        container.setBounds(230, 0, 650, 570);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(21, 21));

        lbl_date.setText("Date");
        jMenuBar1.add(lbl_date);

        lbl_time.setText("Time");
        jMenuBar1.add(lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_transactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transactMousePressed
        container.removeAll();
        resetColor(btn_transfer);
        resetColor(btn_about);
        resetColor(btn_balance);
        setColor(btn_transact);
        resetColor(btn_transfer1);
        CustomerTask.Transaction ob=new CustomerTask.Transaction();
        container.setLayout(new CardLayout());
        container.add(ob);
        container.repaint();
        container.validate();
    }//GEN-LAST:event_btn_transactMousePressed

    private void btn_balanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_balanceMousePressed
        resetColor(btn_transfer);
        resetColor(btn_about);
        setColor(btn_balance);
        resetColor(btn_transfer1);
        resetColor(btn_transact);
        container.removeAll();

        CustomerTask.Balance ob=new CustomerTask.Balance();
        container.setLayout(new CardLayout());

        container.add(ob);
        container.repaint();
        container.validate();     // TODO add your handling code here:
    }//GEN-LAST:event_btn_balanceMousePressed

    private void btn_transferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transferMousePressed
        container.removeAll();
        setColor(btn_transfer);
        resetColor(btn_transfer1);
        resetColor(btn_about);
        resetColor(btn_balance);
        resetColor(btn_transact);
        CustomerTask.Transfer ob=new CustomerTask.Transfer();
        container.setLayout(new CardLayout());
        container.add(ob);
        container.repaint();
        container.validate();
    }//GEN-LAST:event_btn_transferMousePressed

    private void btn_aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMousePressed
      resetColor(btn_transfer);
        setColor(btn_about);
        resetColor(btn_balance);
        resetColor(btn_transact);
        resetColor(btn_transfer1);
        container.removeAll();
        CustomerTask.About ob=new CustomerTask.About();
        container.setLayout(new CardLayout());
        container.add(ob);
        container.repaint();
        container.validate();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aboutMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Login ob=new Login();
       ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_transfer1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transfer1MousePressed
      setColor(btn_transfer1);
        resetColor(btn_about);
        resetColor(btn_balance);
        resetColor(btn_transact); 
Password ob=new Password();
ob.setVisible(true);
        resetColor(btn_transfer);
// TODO add your handling code here:
    }//GEN-LAST:event_btn_transfer1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerTaskFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add2;
    private javax.swing.JLabel Add3;
    private javax.swing.JLabel Add4;
    private javax.swing.JLabel Add5;
    private javax.swing.JLabel Add6;
    private javax.swing.JPanel bgpanel;
    private javax.swing.JPanel btn_about;
    private javax.swing.JPanel btn_balance;
    private javax.swing.JPanel btn_transact;
    private javax.swing.JPanel btn_transfer;
    private javax.swing.JPanel btn_transfer1;
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
class Thred1 extends Thread{
        java.util.Date dt;
        public void run(){ 
          while(true) {
           dt=new java.util.Date();
           String t=""+dt.getHours()+":"+dt.getMinutes()+":"+dt.getSeconds();
           String d=""+dt.getDay()+"/"+(dt.getMonth()+1)+"/"+(dt.getYear()+1900);
           lbl_time.setText(t);
           lbl_date.setText(d);
          }
        }
    }
}
