/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;



import EmployeeTask.Update;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Maa
 */
public class EmployeeTaskFrame extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Main
     */
    public EmployeeTaskFrame() {
        initComponents();
        container.removeAll();
        EmployeeTask.NewAc ob=new EmployeeTask.NewAc();
        container.setLayout(new CardLayout());
        container.add(ob);
        container.repaint();
        container.validate();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        Thred1 ob1;
        ob1 = new Thred1();
        ob1.start();
    }
     void setColor(JPanel panel)
    {
        panel.setBackground(new Color(102,0,102));
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(51,0,51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        side = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_new = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        btn_deposit = new javax.swing.JPanel();
        Add1 = new javax.swing.JLabel();
        btn_withdrawl = new javax.swing.JPanel();
        Add3 = new javax.swing.JLabel();
        btn_transact = new javax.swing.JPanel();
        Add2 = new javax.swing.JLabel();
        btn_balance = new javax.swing.JPanel();
        Add4 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JPanel();
        Add6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_transfer = new javax.swing.JPanel();
        Add5 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        lbl_date = new javax.swing.JMenu();
        lbl_time = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 680));
        setPreferredSize(new java.awt.Dimension(900, 700));
        setSize(new java.awt.Dimension(900, 680));
        getContentPane().setLayout(null);

        side.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/computer.gif"))); // NOI18N

        btn_new.setBackground(new java.awt.Color(102, 0, 102));
        btn_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_newMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_newMousePressed(evt);
            }
        });

        Add.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("New Account");

        javax.swing.GroupLayout btn_newLayout = new javax.swing.GroupLayout(btn_new);
        btn_new.setLayout(btn_newLayout);
        btn_newLayout.setHorizontalGroup(
            btn_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_newLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_newLayout.setVerticalGroup(
            btn_newLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_deposit.setBackground(new java.awt.Color(51, 0, 51));
        btn_deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_depositMousePressed(evt);
            }
        });

        Add1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));
        Add1.setText("Deposit");

        javax.swing.GroupLayout btn_depositLayout = new javax.swing.GroupLayout(btn_deposit);
        btn_deposit.setLayout(btn_depositLayout);
        btn_depositLayout.setHorizontalGroup(
            btn_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_depositLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_depositLayout.setVerticalGroup(
            btn_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_withdrawl.setBackground(new java.awt.Color(51, 0, 51));
        btn_withdrawl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_withdrawlMousePressed(evt);
            }
        });

        Add3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add3.setForeground(new java.awt.Color(255, 255, 255));
        Add3.setText("Withdrawl");

        javax.swing.GroupLayout btn_withdrawlLayout = new javax.swing.GroupLayout(btn_withdrawl);
        btn_withdrawl.setLayout(btn_withdrawlLayout);
        btn_withdrawlLayout.setHorizontalGroup(
            btn_withdrawlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_withdrawlLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_withdrawlLayout.setVerticalGroup(
            btn_withdrawlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_transact.setBackground(new java.awt.Color(51, 0, 51));
        btn_transact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_transactMousePressed(evt);
            }
        });

        Add2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add2.setForeground(new java.awt.Color(255, 255, 255));
        Add2.setText("Transaction");

        javax.swing.GroupLayout btn_transactLayout = new javax.swing.GroupLayout(btn_transact);
        btn_transact.setLayout(btn_transactLayout);
        btn_transactLayout.setHorizontalGroup(
            btn_transactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_transactLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_transactLayout.setVerticalGroup(
            btn_transactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_balance.setBackground(new java.awt.Color(51, 0, 51));
        btn_balance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_balanceMousePressed(evt);
            }
        });

        Add4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add4.setForeground(new java.awt.Color(255, 255, 255));
        Add4.setText("Balance Enquiry");

        javax.swing.GroupLayout btn_balanceLayout = new javax.swing.GroupLayout(btn_balance);
        btn_balance.setLayout(btn_balanceLayout);
        btn_balanceLayout.setHorizontalGroup(
            btn_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_balanceLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add4)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        btn_balanceLayout.setVerticalGroup(
            btn_balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_edit.setBackground(new java.awt.Color(51, 0, 51));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editMousePressed(evt);
            }
        });

        Add6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add6.setForeground(new java.awt.Color(255, 255, 255));
        Add6.setText("Edit Customer");

        javax.swing.GroupLayout btn_editLayout = new javax.swing.GroupLayout(btn_edit);
        btn_edit.setLayout(btn_editLayout);
        btn_editLayout.setHorizontalGroup(
            btn_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_editLayout.setVerticalGroup(
            btn_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_transfer.setBackground(new java.awt.Color(51, 0, 51));
        btn_transfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_transferMousePressed(evt);
            }
        });

        Add5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Add5.setForeground(new java.awt.Color(255, 255, 255));
        Add5.setText("Transfer");

        javax.swing.GroupLayout btn_transferLayout = new javax.swing.GroupLayout(btn_transfer);
        btn_transfer.setLayout(btn_transferLayout);
        btn_transferLayout.setHorizontalGroup(
            btn_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_transferLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Add5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_transferLayout.setVerticalGroup(
            btn_transferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_withdrawl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_transact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideLayout.createSequentialGroup()
                .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_transfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sideLayout.createSequentialGroup()
                        .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sideLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sideLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_withdrawl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_transact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        getContentPane().add(side);
        side.setBounds(0, 0, 240, 650);

        container.setMinimumSize(new java.awt.Dimension(651, 518));
        container.setPreferredSize(new java.awt.Dimension(660, 530));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(container);
        container.setBounds(240, 0, 640, 650);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(21, 21));

        lbl_date.setText("Date");
        jMenuBar1.add(lbl_date);

        lbl_time.setText("Time");
        jMenuBar1.add(lbl_time);

        jMenu1.setText("Profile");

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Change Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_depositMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_depositMousePressed
        container.removeAll();
        setColor(btn_deposit);
        resetColor(btn_transfer);
        resetColor(btn_new);
        resetColor(btn_transact);
         resetColor(btn_withdrawl);
        resetColor(btn_balance);
         resetColor(btn_edit);
        EmployeeTask.Deposit ob=new EmployeeTask.Deposit();
        container.setLayout(new CardLayout());
        container.add(ob);
        container.repaint();
        container.validate();

    }//GEN-LAST:event_btn_depositMousePressed

    private void btn_transactMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transactMousePressed
        container.removeAll();
        setColor(btn_transact);
        resetColor(btn_deposit);
        resetColor(btn_new);
        resetColor(btn_transfer);
         resetColor(btn_withdrawl);
        resetColor(btn_balance);
         resetColor(btn_edit);
       EmployeeTask.Transaction ob=new EmployeeTask.Transaction();
        container.setLayout(new CardLayout());
        container.add(ob);
        container.repaint();
        container.validate();
    }//GEN-LAST:event_btn_transactMousePressed

    private void btn_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMouseClicked
        // TODO addemp your handling code here:
    }//GEN-LAST:event_btn_newMouseClicked

    private void btn_newMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMousePressed

       resetColor(btn_deposit);
        setColor(btn_new);
        resetColor(btn_transact);
         resetColor(btn_withdrawl);
        resetColor(btn_balance);
         resetColor(btn_edit);
         resetColor(btn_transfer);
        container.removeAll();

        EmployeeTask.NewAc ob=new EmployeeTask.NewAc();
        container.setLayout(new CardLayout());
        container.add(ob);
        container.repaint();
        container.validate();

    }//GEN-LAST:event_btn_newMousePressed

    private void btn_withdrawlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_withdrawlMousePressed
       resetColor(btn_deposit);
        resetColor(btn_new);
        resetColor(btn_transact);
         setColor(btn_withdrawl);
        resetColor(btn_balance);
         resetColor(btn_edit);
         resetColor(btn_transfer);
        container.removeAll();

        EmployeeTask.Withdrawl ob=new EmployeeTask.Withdrawl();
        container.setLayout(new CardLayout());

        container.add(ob);
        container.repaint();
        container.validate(); // TODO add your handling code here:
    }//GEN-LAST:event_btn_withdrawlMousePressed

    private void btn_balanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_balanceMousePressed
        resetColor(btn_transfer);
        resetColor(btn_deposit);
        resetColor(btn_new);
        resetColor(btn_transact);
         resetColor(btn_withdrawl);
        setColor(btn_balance);
         resetColor(btn_edit);
        container.removeAll();

        EmployeeTask.Balance ob=new EmployeeTask.Balance();
        container.setLayout(new CardLayout());

        container.add(ob);
        container.repaint();
        container.validate();     // TODO add your handling code here:
    }//GEN-LAST:event_btn_balanceMousePressed

    private void btn_editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMousePressed
    resetColor(btn_transfer);
        resetColor(btn_deposit);
        resetColor(btn_new);
        resetColor(btn_transact);
         resetColor(btn_withdrawl);
        resetColor(btn_balance);
         setColor(btn_edit);
 container.removeAll();// TODO add your handling code here:
          EmployeeTask.Edit_Customer ob=new EmployeeTask.Edit_Customer();
          container.setLayout(new CardLayout());

        container.add(ob);
        container.repaint();
        container.validate();
    }//GEN-LAST:event_btn_editMousePressed

    private void btn_transferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transferMousePressed
      setColor(btn_transfer);
        resetColor(btn_deposit);
        resetColor(btn_new);
        resetColor(btn_transact);
         resetColor(btn_withdrawl);
        resetColor(btn_balance);
         resetColor(btn_edit); 
        container.removeAll();

        EmployeeTask.Transfer ob=new EmployeeTask.Transfer();
        container.setLayout(new CardLayout());
        container.add(ob);
        container.repaint();
        container.validate();         
// TODO add your handling code here:
    }//GEN-LAST:event_btn_transferMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     EmployeeTask.About1 ob=new EmployeeTask.About1();
        ob.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       Update ob=new Update();
      ob.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeTaskFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add1;
    private javax.swing.JLabel Add2;
    private javax.swing.JLabel Add3;
    private javax.swing.JLabel Add4;
    private javax.swing.JLabel Add5;
    private javax.swing.JLabel Add6;
    private javax.swing.JPanel btn_balance;
    private javax.swing.JPanel btn_deposit;
    private javax.swing.JPanel btn_edit;
    private javax.swing.JPanel btn_new;
    private javax.swing.JPanel btn_transact;
    private javax.swing.JPanel btn_transfer;
    private javax.swing.JPanel btn_withdrawl;
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu lbl_date;
    private javax.swing.JMenu lbl_time;
    private javax.swing.JPanel side;
    // End of variables declaration//GEN-END:variables
class Thred1 extends Thread{
        java.util.Date dt;
        public void run(){ 
          while(true) {
           dt=new java.util.Date();
           String t=""+dt.getHours()+":"+dt.getMinutes()+":"+dt.getSeconds();
           String d=""+dt.getDay()+"/"+(dt.getMonth()+1)+"/"+(dt.getYear()+1900);
           lbl_time.setText(t);
           lbl_date.setText(d);
          }
        }
    }
}
