/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminTask;



import java.sql.*;

import javax.swing.*;

/**
 *
 * @author Maa
 */
public class EditEmp_panel extends javax.swing.JPanel {

    /**
     * Creates new form Edit1
     */
    public EditEmp_panel() {
        initComponents();
       Adminlb.setText( Admindash.Adminname);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditEmp_panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextArea();
        fathernametxt = new javax.swing.JTextField();
        mobiletxt = new javax.swing.JTextField();
        emailidtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maleradio = new javax.swing.JRadioButton();
        femaleradio = new javax.swing.JRadioButton();
        edit2_reset = new javax.swing.JButton();
        edit_update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pintxt = new javax.swing.JTextField();
        statetxt = new javax.swing.JTextField();
        citytxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dobtxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        edit_find = new javax.swing.JButton();
        nametxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Adminlb = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        EditEmp_panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EditEmp_panel.setMinimumSize(new java.awt.Dimension(680, 560));
        EditEmp_panel.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Father's Name");
        EditEmp_panel.add(jLabel13);
        jLabel13.setBounds(80, 220, 100, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Gender");
        EditEmp_panel.add(jLabel14);
        jLabel14.setBounds(80, 260, 90, 30);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Mobile No.");
        EditEmp_panel.add(jLabel15);
        jLabel15.setBounds(80, 390, 100, 30);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setText("Date of Birth*");
        EditEmp_panel.add(jLabel16);
        jLabel16.setBounds(80, 350, 100, 30);

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setText("Email id");
        EditEmp_panel.add(jLabel17);
        jLabel17.setBounds(80, 300, 90, 30);

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setText("Address");
        EditEmp_panel.add(jLabel18);
        jLabel18.setBounds(80, 430, 90, 30);

        addresstxt.setColumns(20);
        addresstxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addresstxt.setRows(5);
        addresstxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(addresstxt);
        addresstxt.setBounds(190, 430, 190, 70);

        fathernametxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        fathernametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(fathernametxt);
        fathernametxt.setBounds(190, 220, 300, 30);

        mobiletxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        mobiletxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(mobiletxt);
        mobiletxt.setBounds(190, 300, 300, 30);

        emailidtxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        emailidtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(emailidtxt);
        emailidtxt.setBounds(190, 390, 190, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("* Including sur name");
        EditEmp_panel.add(jLabel2);
        jLabel2.setBounds(30, 510, 180, 14);

        maleradio.setText("Male");
        maleradio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        maleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleradioActionPerformed(evt);
            }
        });
        EditEmp_panel.add(maleradio);
        maleradio.setBounds(210, 260, 70, 30);

        femaleradio.setText("Female");
        femaleradio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        femaleradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleradioActionPerformed(evt);
            }
        });
        EditEmp_panel.add(femaleradio);
        femaleradio.setBounds(370, 260, 80, 30);

        edit2_reset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        edit2_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/erase-128.png"))); // NOI18N
        edit2_reset.setText("Reset");
        edit2_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2_resetActionPerformed(evt);
            }
        });
        EditEmp_panel.add(edit2_reset);
        edit2_reset.setBounds(510, 200, 100, 30);

        edit_update.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        edit_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update icon.png"))); // NOI18N
        edit_update.setText("Update");
        edit_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_updateActionPerformed(evt);
            }
        });
        EditEmp_panel.add(edit_update);
        edit_update.setBounds(510, 270, 100, 30);

        jLabel3.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel3.setText("city");
        EditEmp_panel.add(jLabel3);
        jLabel3.setBounds(400, 390, 50, 30);

        jLabel21.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel21.setText("State");
        EditEmp_panel.add(jLabel21);
        jLabel21.setBounds(400, 430, 50, 30);

        jLabel11.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jLabel11.setText("Pin");
        EditEmp_panel.add(jLabel11);
        jLabel11.setBounds(400, 470, 40, 30);

        pintxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(pintxt);
        pintxt.setBounds(470, 470, 120, 30);

        statetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(statetxt);
        statetxt.setBounds(470, 430, 120, 30);

        citytxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(citytxt);
        citytxt.setBounds(470, 390, 120, 30);

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Employee");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 250, 44);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 250, 10);

        EditEmp_panel.add(jPanel1);
        jPanel1.setBounds(0, 50, 680, 50);

        dobtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(dobtxt);
        dobtxt.setBounds(190, 350, 230, 30);

        jLabel20.setText("* Please keep dob (yyyy-mm-dd)");
        EditEmp_panel.add(jLabel20);
        jLabel20.setBounds(430, 360, 160, 14);

        usernametxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        usernametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditEmp_panel.add(usernametxt);
        usernametxt.setBounds(190, 120, 263, 30);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setText("User id");
        EditEmp_panel.add(jLabel19);
        jLabel19.setBounds(80, 120, 100, 30);

        edit_find.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        edit_find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search.png"))); // NOI18N
        edit_find.setText("Find");
        edit_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_findActionPerformed(evt);
            }
        });
        EditEmp_panel.add(edit_find);
        edit_find.setBounds(500, 130, 120, 30);

        nametxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nametxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        EditEmp_panel.add(nametxt);
        nametxt.setBounds(190, 170, 263, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Full Name");
        EditEmp_panel.add(jLabel10);
        jLabel10.setBounds(80, 170, 58, 30);

        jLabel39.setText("Logged in As :");
        EditEmp_panel.add(jLabel39);
        jLabel39.setBounds(0, 0, 80, 20);

        Adminlb.setText("emp");
        EditEmp_panel.add(Adminlb);
        Adminlb.setBounds(80, 0, 150, 20);

        add(EditEmp_panel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void edit_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_findActionPerformed
        try{
            Main.Database ob= new Main.Database();
            Connection con=DriverManager.getConnection(ob.Url+ob.Db,ob.Userid,ob.Password);
            Statement st=con.createStatement();
            String query="Select *from Employee where username='"+usernametxt.getText()+"'";

            ResultSet rs=st.executeQuery(query);
            while(rs.next()){
                nametxt.setText(rs.getString(1));
                fathernametxt.setText(rs.getString(3));
                dobtxt.setText(rs.getString(5));
                
                String gender=rs.getString(4);
                if(gender.equals("male")){
                    maleradio.setSelected(true);
                }else{
                    femaleradio.setSelected(true);
                }
                mobiletxt.setText(rs.getString(6));
                emailidtxt.setText(rs.getString(7));
                addresstxt.setText(rs.getString(8));
                citytxt.setText(rs.getString(9));
                statetxt.setText(rs.getString(10));
                pintxt.setText(rs.getString(11));

            }

        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }        // TODO addemp your handling code here:
    }//GEN-LAST:event_edit_findActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO addemp your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void edit2_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2_resetActionPerformed
        nametxt.setText("");
        usernametxt.setText("");
        fathernametxt.setText("");
        maleradio.setSelected(false);
        femaleradio.setSelected(false);
        dobtxt.setText("");

        mobiletxt.setText("");
        emailidtxt.setText("");
        addresstxt.setText("");
        citytxt.setText("");
        statetxt.setText("");
        pintxt.setText("");
    }//GEN-LAST:event_edit2_resetActionPerformed

    private void edit_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_updateActionPerformed
       int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
            Main.Database ob=new Main.Database();
            Class.forName(ob.Driver);
            Connection con=DriverManager.getConnection(ob.Url+ob.Db,ob.Userid,ob.Password);

            String query="Update Employee set Name =?,Father_name=?,gender=?,dob=?,Mobile_no=?,Email_id=?,address=?,city=?,state=?,pin=? where username='"+usernametxt.getText()+"'";
            PreparedStatement pst=con.prepareStatement(query);

            pst.setString(1, nametxt.getText());
            pst.setString(2,fathernametxt.getText());
            String gender;
            if(femaleradio.isSelected()){
                gender="female";}
            else{
                gender="male"; }
            pst.setString(3,gender);
            String dob="";
            dob =dobtxt.getText();

            pst.setString(4,dob);

            pst.setString(5,mobiletxt.getText());
            pst.setString(6,emailidtxt.getText());
            pst.setString(7,addresstxt.getText());
            pst.setString(8,citytxt.getText());
            pst.setString(9,statetxt.getText());
            pst.setString(10,pintxt.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Update Successful");
        }

        catch( ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        } // TODO addemp your handling code here:
    }//GEN-LAST:event_edit_updateActionPerformed

    private void femaleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleradioActionPerformed
      if(femaleradio.isSelected())
        {
            maleradio.setSelected(false); }  // TODO add your handling code here:
    }//GEN-LAST:event_femaleradioActionPerformed

    private void maleradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleradioActionPerformed
        if(maleradio.isSelected())
        {
            femaleradio.setSelected(false); }        // TODO add your handling code here:
    }//GEN-LAST:event_maleradioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adminlb;
    private javax.swing.JPanel EditEmp_panel;
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JTextField citytxt;
    private javax.swing.JTextField dobtxt;
    private javax.swing.JButton edit2_reset;
    private javax.swing.JButton edit_find;
    private javax.swing.JButton edit_update;
    private javax.swing.JTextField emailidtxt;
    private javax.swing.JTextField fathernametxt;
    private javax.swing.JRadioButton femaleradio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton maleradio;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField pintxt;
    private javax.swing.JTextField statetxt;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
